### PR TITLE
Added Django server as the backend and a basic upload 

### PR DESCRIPTION
**Pull request by anshabhi**
Hello,

I am Abhinav Agarwal. 

In this pull request I have added:
1. Django as the backend http server for AITom GUI. 
2. Added functionality to upload a .mrc file and view it in the browser.

### CODE REVIEW

**Comment by xulabs** [comment]
@anshabhi thanks. to keep our AITom codebase lean and clean, we only keep source code and text files. Can you remove other files, such as figures and data files? Can find some ways to patch these non-text files to the downloaded AITom library.

**Comment by anshabhi** [comment]
Hello,

I have now removed all non-text files from the repository, and I have provided alternate links where they could be accessed from.

Thanks

**Comment by xulabs** [comment]
Thanks. Are there any remaining source code that is directly copied from somewhere? We will also need to remove them to prevent license issues.

**Comment by anshabhi** [comment]
Hello,

There is some open-source code that has been used. Namely, it is from the following sources:

1. [three.js](https://github.com/mrdoob/three.js) : three.js library, plug-ins and HTML page css/design taken. MIT License
2. [Simple File Upload](https://github.com/sibtc/simple-file-upload): a small tutorial for uploading files using django, I used some parts from this tutorial in the code. MIT License

As of now, there is no code from other sources. The backend code is being designed by @CCDV2 . 

I have added a `license.md` file to the root directory which should satisfy the requirements for MIT license.

I will take care to add appropriate attributions, for open source code, that we might use in the future. I will never use any proprietary code for the project.

Thank You!

**Comment by xulabs** [comment]
Ok. I saw most of the code are inside aitom/gui/gui. Would it be more appropriate if we move the code to aitom/gui/backend? Currently we are developing internet browser based gui. Later on we may have other forms of guy, especially local ones, as well.

**Comment by xulabs** [comment]
Also, the root of AITom has a GNU license and the aitom/gui has a MIT license. Would this lead to any conflict?

**Comment by anshabhi** [comment]
Hello Sir,

regarding the license,  as of now we have not added any license to aitom/gui, so it should be under GNU only like the rest of AItom repo. `license.md` file only contains attributions for other libraries. It doesn't provide a different license to aitom/gui

In future, if we have to distribute locally, we will have 2 options:

1. Use something like [nwjs](https://nwjs.io/), which packages the application with a chromium-based node.js enabled browser, and allows us to reuse the same code for website, for local use. We will only have to work on providing python for the backend.

2. Redesign the application entirely using [Qt](https://www.qt.io/) or a similar python-based GUI framework.

Currently, by backend, we are referring to the scripts that will process the MRC files.

Please let me know if it would be better to divide the scripts into 3 folders:
1. backend - python scripts for processing the mrc files
2. server - django server scripts for communicating between HTML pages and backend python scripts. (currently its a part of `gui` folder only)
3. frontend -  HTML/CSS/JS scripts, the main browser-based UI 

There are many folders which have `/gui` as a sub-directory. such as `/static/gui/css` or `/templates/gui`. This is a requirement from Django to avoid naming conflicts. I can rename `gui` to avoid confusion.

Thank you very much for time sir.

**Pull request merged**
